name: Build Scores

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LilyPond
        run: |
          sudo apt-get update
          sudo apt-get install -y lilypond

      - name: Avoid Lilypond version issues
        run: |
          find . -name "*.ly" -type f | while read -r file; do
              echo "Processing $file"
              convert-ly -e -c "$file"
          done

      - name: Generate PDFs and MIDIs
        run: |
          find . -name "*.ly" -type f | while read -r file; do
              echo "Processing $file"
              pushd "$(dirname "$file")"
              lilypond -dno-point-and-click "$(basename "$file")"
              popd
          done

      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          cargo install mdbook

      - name: Build pages with mdBook
        run: |
          . "$HOME/.cargo/env"
          mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
      

      # - name: Upload generated files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: scores
      #     path: |
      #       **/*.pdf
      #       **/*.midi
  # deploy:
  #   # Add a dependency to the build job
  #   needs: build

  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source

  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action