name: Build Scores

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LilyPond
        uses: codello/setup-lilypond@main
        with:
          lilypond-version: 2.24

      - name: Avoid Lilypond version issues
        run: |
          find . -name "*.ly" -type f | while read -r file; do
              echo "Processing $file"
              convert-ly -e -c "$file"
          done

      - name: Generate PDFs, MIDIs and PNGs
        run: |
          find . -name "*.ly" -type f | while read -r file; do
              echo "Processing $file"
              pushd "$(dirname "$file")"
              lilypond -dno-point-and-click \
                       --formats=pdf,midi,png \
                       "$(basename "$file")"
              popd
          done

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Generate index
        run: |
          python make_toc.py scores "${{ github.server_url }}/${{ github.repository }}" --branch "${{ github.ref_name }}"
      
      - name: Create html index
        run: |
          apt-get update && apt-get install -y pandoc
          cd scores
          pandoc -s -o index.html index.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scores
          path: ./scores

  # deploy:
  #   # Add a dependency to the build job
  #   needs: build

  #   # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  #   permissions:
  #     pages: write      # to deploy to Pages
  #     id-token: write   # to verify the deployment originates from an appropriate source

  #   # Deploy to the github-pages environment
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   # Specify runner + deployment step
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action